In [1]:
import numpy

## Index İle Eleman İşleme

In [2]:
a = numpy.random.randint(10, size = 10)

In [3]:
a

array([9, 6, 1, 0, 7, 4, 2, 3, 6, 8])

In [4]:
a[0]

9

In [5]:
a[-1]

8

In [6]:
a[0] = 3

In [7]:
a

array([3, 6, 1, 0, 7, 4, 2, 3, 6, 8])

In [8]:
m = numpy.random.randint(10, size = (3, 5))

In [9]:
m

array([[6, 9, 7, 1, 1],
       [3, 9, 1, 3, 2],
       [1, 0, 3, 6, 6]])

In [10]:
m[0, 0]

6

In [12]:
m[0, 0] = 8

In [13]:
m

array([[8, 9, 7, 1, 1],
       [3, 9, 1, 3, 2],
       [1, 0, 3, 6, 6]])

In [14]:
m[1, 1] = 8.7

In [15]:
m

array([[8, 9, 7, 1, 1],
       [3, 8, 1, 3, 2],
       [1, 0, 3, 6, 6]])

## Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [39]:
b = numpy.arange(20, 30) #tek boyutlu slice işlemleri

In [17]:
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
b[0:3]

array([20, 21, 22])

In [19]:
b[:3]

array([20, 21, 22])

In [20]:
b[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [21]:
b[1::2]

array([21, 23, 25, 27, 29])

In [35]:
b[-5: -2]

array([25, 26, 27])

In [38]:
b[:-1]

array([20, 21, 22, 23, 24, 25, 26, 27, 28])

In [30]:
b[-2: -1]

array([28])

In [40]:
m = numpy.random.randint(10, size = (5, 5))

In [41]:
m

array([[2, 7, 3, 1, 7],
       [7, 7, 9, 5, 0],
       [7, 1, 5, 5, 6],
       [9, 9, 6, 4, 8],
       [5, 8, 7, 2, 5]])

In [44]:
m[:, 0]

array([2, 7, 7, 9, 5])

In [45]:
m[:, 1]

array([7, 7, 1, 9, 8])

In [46]:
m[0, :]

array([2, 7, 3, 1, 7])

In [48]:
m[0:2, 0:2]

array([[2, 7],
       [7, 7]])

## Alt Küme Üzerinde İşlem Yapmak

In [49]:
c = numpy.random.randint(10, size = (5, 5))

In [50]:
c

array([[3, 0, 8, 2, 6],
       [5, 5, 9, 9, 8],
       [8, 2, 1, 9, 1],
       [2, 3, 5, 5, 5],
       [5, 5, 1, 7, 8]])

In [51]:
alt_c = c[0:3, 0:3]

In [52]:
alt_c

array([[3, 0, 8],
       [5, 5, 9],
       [8, 2, 1]])

In [55]:
alt_c[0,0] = 1

In [56]:
alt_c

array([[1, 0, 8],
       [5, 5, 9],
       [8, 2, 1]])

In [57]:
c #ana arrayde de değişiklik meydana geldi

array([[1, 0, 8, 2, 6],
       [5, 5, 9, 9, 8],
       [8, 2, 1, 9, 1],
       [2, 3, 5, 5, 5],
       [5, 5, 1, 7, 8]])

In [60]:
alt_c_copy = c[3:5, 3:5].copy()

In [61]:
alt_c_copy

array([[5, 5],
       [7, 8]])

In [64]:
alt_c_copy[0,0] = 1

In [65]:
alt_c_copy

array([[1, 5],
       [7, 8]])

In [66]:
c

array([[1, 0, 8, 2, 6],
       [5, 5, 9, 9, 8],
       [8, 2, 1, 9, 1],
       [2, 3, 5, 5, 5],
       [5, 5, 1, 7, 8]])

## Fancy Index ile Elemanlara Erişmek

In [67]:
v = numpy.arange(0, 31, 3) #tek boyutta

In [68]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [69]:
v[1]

3

In [73]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [71]:
al_getir = [1, 3, 5]

In [72]:
v[al_getir]

array([ 3,  9, 15])

In [85]:
mat = numpy.arange(0,9).reshape(3,3) #iki boyutta

In [75]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
satir = numpy.array([0,1])

In [83]:
sutun = numpy.array([1,2])

In [84]:
mat[satir, sutun]

array([1, 5])

In [91]:
mat[0:, [1,2]] #slice ile fancy

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu Eleman İşlemleri

In [92]:
array = numpy.array([1, 2, 3, 4, 5])

In [102]:
array > 3

array([False, False, False,  True,  True])

In [103]:
array[array > 3]

array([4, 5])

## Matematiksel İşlemler

In [106]:
array - 1

array([0, 1, 2, 3, 4])

In [107]:
array * 2

array([ 2,  4,  6,  8, 10])

In [108]:
array / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [109]:
#ufunc

In [110]:
numpy.subtract(array, 1)

array([0, 1, 2, 3, 4])

In [111]:
numpy.add(array, 1)

array([2, 3, 4, 5, 6])

In [112]:
numpy.multiply(array, 2)

array([ 2,  4,  6,  8, 10])

In [113]:
numpy.divide(array, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [114]:
numpy.power(array, 2)

array([ 1,  4,  9, 16, 25])

In [115]:
numpy.mod(array, 2)

array([1, 0, 1, 0, 1])

In [117]:
numpy.absolute(numpy.array([-3]))

array([3])

In [123]:
numpy.sin(360)

0.9589157234143065

In [127]:
numpy.log2([1, 2, 3])

array([0.       , 1.       , 1.5849625])

## NumPy ile İki Bilinmeyenli Denklem Çözümü

- 5 * x0 + x1 = 12
- x0 + 3 * x1 = 10

In [135]:
kat_sayi = numpy.array([[5, 1], [1, 3]])
deger = numpy.array([12, 10])

In [138]:
numpy.linalg.solve(kat_sayi, deger)

array([1.85714286, 2.71428571])

In [132]:
#genel dokümantasyon

In [133]:
?numpy