## Örnekler

In [1]:
#1: Dizi oluşturma ve işleme

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
squared = np.square(arr)

print(squared)

[ 1  4  9 16 25]


In [3]:
#2: Matris çarpma

In [4]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a,b)

print(result)

[[19 22]
 [43 50]]


In [5]:
#3 İstatiksel hesaplamalar

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)

print(mean)

3.0


In [7]:
#4 Dizi işlemleri

In [8]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b

print(c)

[5 7 9]


In [9]:
#5 Görüntü işleme

In [10]:
import numpy as np
from PIL import Image, ImageFilter

img = Image.open('image.jpeg')
img_arr = np.array(img)

img_gaussian = Image.fromarray(img_arr)
img_gaussian = img_gaussian.filter(ImageFilter.GaussianBlur(radius=5))
img_gaussian_arr = np.array(img_gaussian)

img_arr[100:150, 200:250, 0] = 255  # Kırmızı
img_arr[100:150, 200:250, 1] = 0    # Yeşil
img_arr[100:150, 200:250, 2] = 0    # Mavi

img_result = Image.fromarray(img_arr)
img_result.save('result.jpg')

img_gaussian_result = Image.fromarray(img_gaussian_arr)
img_gaussian_result.save('result_gaussian.jpg')