In [1]:
import numpy

In [7]:
#liste üzerinden array oluşturma

In [2]:
a = numpy.array([1, 2, 3, 4, 5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = numpy.array([3.14, 7, 2])

In [6]:
b

array([3.14, 7.  , 2.  ])

In [8]:
#sıfırdan array oluşturma

In [10]:
numpy.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
numpy.ones((3, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
numpy.full((5, 3), 5) #herhangi bir sayı ile oluşturma

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
numpy.arange(0, 31, 3) #doğrusal dizi

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
numpy.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
numpy.random.normal(10, 4, (3, 4)) #ortalama 10, standart sapma 4

array([[ 7.95970278,  5.96822947, 12.3013385 , 11.33785023],
       [ 5.10796087, -3.34820671, 10.16690618, 10.3085423 ],
       [12.6391454 ,  8.21879419, 13.47768132, 12.9189777 ]])

In [19]:
numpy.random.randint(0, 10, (3, 3))

array([[4, 5, 3],
       [9, 5, 9],
       [9, 8, 4]])

## Özellikler

* ndim: _boyut sayısı_
* shape: _boyut bilgisi_
* size: _toplam eleman sayısı_
* dtype: _array veri tipi_

In [25]:
array = numpy.random.randint(0, 10, (3, 4))

In [26]:
array

array([[5, 1, 3, 7],
       [3, 6, 4, 5],
       [4, 3, 0, 2]])

In [28]:
array.ndim #matrix

2

In [29]:
array.shape

(3, 4)

In [30]:
array.size

12

In [31]:
array.dtype

dtype('int64')