## Yeniden Şekillendirme (reshaping)

In [1]:
import numpy

In [3]:
a = numpy.arange(1, 10)

In [4]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a.reshape((1,9)) #tek boyuttan çok boyuta

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
a.reshape((1,9)).ndim

2

## Array Birleştirme (Concatenation)

In [9]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])

In [11]:
numpy.concatenate([x, y]) #tek boyutta birleştirme

array([1, 2, 3, 4, 5, 6])

In [12]:
a = numpy.array([[1, 2, 3],
                 [4, 5, 6]])

In [13]:
numpy.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [15]:
numpy.concatenate([a, a], axis = 0) #satır

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
numpy.concatenate([a, a], axis = 1) #sütün

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [21]:
z = numpy.array([1, 2, 3, 99, 99, 3, 2, 1])

In [23]:
numpy.split(z, [3, 5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [24]:
d, e, f = numpy.split(z, [3, 5])

In [25]:
d

array([1, 2, 3])

In [26]:
m = numpy.arange(16).reshape(4, 4)

In [27]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
numpy.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [35]:
ust, alt = numpy.vsplit(m, [2])

In [34]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
numpy.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [39]:
sag, sol = numpy.hsplit(m, [2])

In [44]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

## Array Sıralama (Sorting)

In [51]:
v = numpy.array([2, 1, 4, 3, 5]) #tek boyutlu

In [47]:
numpy.sort(v)

array([1, 2, 3, 4, 5])

In [48]:
v

array([2, 1, 4, 3, 5])

In [49]:
v.sort()

In [50]:
v

array([1, 2, 3, 4, 5])

In [52]:
mat = numpy.random.normal(20, 5, (3, 3))

In [53]:
mat

array([[19.10685304, 27.8263615 , 24.12950753],
       [24.49665734, 14.08363086, 22.25006929],
       [19.86245961, 24.38812106, 13.19471657]])

In [54]:
numpy.sort(mat, axis = 1)

array([[19.10685304, 24.12950753, 27.8263615 ],
       [14.08363086, 22.25006929, 24.49665734],
       [13.19471657, 19.86245961, 24.38812106]])